spring:
  application:
    name: provider
dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.huang.provider.serviceimpl